### ISSUE TITLE
Negotiation constraint (composer)

### ISSUE THREAD

**Issue by willdurand** [rszrama/negotiation-middleware#1]
Hi Ryan! Nice work here ;-)

One remark though: it would be better not to use `dev-master` in your `composer.json` files. It is "bad" as things can break for some reasons, and without you noticing anything. Generally speaking, relying on proper version numbers (such as tags) is better, even for unstable releases of a package. For Negotiation, you should require `willdurand/negotiation:v2.0.0-alpha1`.

William

**Comment by rszrama** [comment]
Nice, thanks! Still getting used to composer / packagist. :smiley:

**Comment by rszrama** [comment]
Alrighty, fixed. I suppose it's the same as with module version numbers in Drupal's drush make. So much to learn. :smile:
